swagger: '2.0'
host: localhost:8081
basePath: /basePath
x-generator-properties:
  business-unit: mybu
  osgi:
    architecture-type: online
    cxf-address: /AddressMinimal
    cxf-context: /ContextMinimal
schemes:
 - http
consumes:

produces:

info:
  version: 0.0.0
  title: Minimal-API-OSGi
  description: my project description
  contact:
    name: Francisco Manuel Benitez Chico
    email: paco.benitez.chico@gmail.com
    url: http://www.pacobenitezchico.com
paths:
  /mainPath:
    get:
      operationId: myOperationName
      responses:
        - 200:
            description: OK