swagger: '2.0'
info:
  version: 1.0.0
  title: ArraysTest
  description: This example about arrays multidimensionals
  contact:
    name: Francisco Manuel Benitez Chico
    email: paco.benitez.chico@gmail.com
    url: http://www.pacobenitezchico.com
host: localhost:8060
x-generator-properties:
  business-unit: mybu
basePath: /arrays
schemes:
 - http
consumes:

produces:

paths:
  /differentDimensionsRequest:
    get:
      operationId: differentDimensionsRequest
      parameters:
        - name: exampleBooleanOneDimensions
          in: query
          type: array
          items:
            type: boolean
        - name: exampleIntegerTwoDimensions
          in: query
          type: array
          items:
            type: array
            items:
              type: integer
              format: int32
        - name: exampleLongThreeDimensions
          in: query
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: integer
                format: int64
        - name: exampleDoubleFourDimensions
          in: query
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: array
                items:
                  type: number
                  format: double
      responses:
        - 200:
            description:  Array of complex object
            schema:
              type: array
              items:
                $ref: '#/definitions/MyObjectArrayRefTwoDimensions'
  /bodyParameterAsSimpleType:
    post:
      operationId: bodyParameterAsSimpleType
      consumes:
        - application/json
      parameters:
        - name: bodyParameter
          in: body
          schema:
            type: boolean
      responses:
        - 200:
            description:  Array of complex object
            schema:
              type: array
              items:
                $ref: '#/definitions/MyObjectArrayRefTwoDimensions'                
  /bodyParameterAsArray:
    post:
      operationId: bodyParameterAsArray
      consumes:
        - application/json
      parameters:
        - name: bodyParameter
          in: body
          schema:
            type: array
            items:
              type: boolean
      responses:
        - 200:
            description:  Array of complex object
            schema:
              type: array
              items:
                $ref: '#/definitions/MyObjectArrayRefTwoDimensions'
  /oneDimensionResponse:
    get:
      operationId: oneDimensionResponse
      parameters:
      
      responses:
        - 200:
            description: one dimension response of boolean
            schema:
              type: array
              items:
                type: boolean
  /twoDimensionsResponse:
    get:
      operationId: twoDimensionsResponse
      parameters:
      
      responses:
        - 200:
            description: one dimension response of boolean
            schema:
              type: array
              items:
                type: array
                items:
                  type: integer
                  format: int32
definitions:
  MyObject:
    type: object
    properties:
      myOneDimensionsStringArray:
        type: array
        items:
          type: string    
      myTwoDimensionsBooleanArray:
        type: array
        items:
          type: array
          items:
            type: boolean
      myThreeDimensionsIntegerArray:
        type: array
        items:
          type: array
          items:
            type: array
            items:
              type: integer
      myThreeDimensionsLongArray:
        type: array
        items:
          type: array
          items:
            type: array
            items:
              type: integer
              format: int64
      myThreeDimensionsFloatArray:
        type: array
        items:
          type: array
          items:
            type: array
            items:
              type: number
              format: float
      myForthDimensionsDoubleArray:
        type: array
        items:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
                format: double
  MyObjectRef:
    $ref: '#/definitions/MyObject'
  MyObjectArrayRefTwoDimensions:
    type: object
    properties:
      myRefArrayTwoDimensions:
        type: array
        items:
          type: array
          items:
            $ref: '#/definitions/MyObjectRef'
