---
swagger: '2.0'
host: localhost:8081
x-generator-properties:
  business-unit: mybu
  osgi:
    architecture-type: online
    cxf-address: /AddressEcho
    cxf-context: /ContextEcho
basePath: /echo
info:
  version: 1.0.0
  title: Echo-OSGi
  description: Echos for different operations
  contact:
    name: Francisco Manuel Benitez Chico
    email: paco.benitez.chico@gmail.com
    url: http://www.pacobenitezchico.com
schemes:
 - http
consumes:

produces:

paths:
  /echoPath:
    get:
      operationId: rootGetOperation
      responses:
        - 200:
            description: Echo GET
    post:
      operationId: rootPostOperation
      consumes:
        - multipart/form-data      
      parameters:
        - name: paramName
          in: formData
          description: name
          type: string
        - name: year
          in: formData
          description: year
          type: string
      responses:
        - 200:
            description: Echo POST          
  /test-path/{id}:
    parameters:
      - name: id
        in: path
        description: ID
        type: string
        required: true
    get:
      operationId: testPathGetOperation
      responses:
        - 200:
            description: Echo test-path
